// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAZnCW6gXkr2nx1i2NLA6au2Z-1lOJAM',
    appId: '1:1085111655534:web:5d01053e1d5df6e0395a7f',
    messagingSenderId: '1085111655534',
    projectId: 'sturdy-yen-362804',
    authDomain: 'sturdy-yen-362804.firebaseapp.com',
    storageBucket: 'sturdy-yen-362804.firebasestorage.app',
    measurementId: 'G-J5CHMD09EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-o8fpa4p6yaI7ItXkUN8g8f__ibn8Tc',
    appId: '1:1085111655534:android:d3e9ee9d07b561af395a7f',
    messagingSenderId: '1085111655534',
    projectId: 'sturdy-yen-362804',
    storageBucket: 'sturdy-yen-362804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_mBF0G3prnSXSqGiRcc2gN7ypTMgxnyw',
    appId: '1:1085111655534:ios:ad320df0d6620926395a7f',
    messagingSenderId: '1085111655534',
    projectId: 'sturdy-yen-362804',
    storageBucket: 'sturdy-yen-362804.firebasestorage.app',
    iosBundleId: 'com.example.miAppHabitos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_mBF0G3prnSXSqGiRcc2gN7ypTMgxnyw',
    appId: '1:1085111655534:ios:ad320df0d6620926395a7f',
    messagingSenderId: '1085111655534',
    projectId: 'sturdy-yen-362804',
    storageBucket: 'sturdy-yen-362804.firebasestorage.app',
    iosBundleId: 'com.example.miAppHabitos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJAZnCW6gXkr2nx1i2NLA6au2Z-1lOJAM',
    appId: '1:1085111655534:web:b911623ef1427fb1395a7f',
    messagingSenderId: '1085111655534',
    projectId: 'sturdy-yen-362804',
    authDomain: 'sturdy-yen-362804.firebaseapp.com',
    storageBucket: 'sturdy-yen-362804.firebasestorage.app',
    measurementId: 'G-93K4D4C65E',
  );
}
